spring:
  application:
    name: microservice-infrastructure
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: SYSTEM
    password: peng414607
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
mybatis:
  mapper-locations: classpath:mapper/*.xml
