mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  application:
    name: eureka-group
  profiles:
    active: peer2
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: SYSTEM
    password: peng414607
    driver-class-name: oracle.jdbc.OracleDriver

--- 
server:
  port: 8761
spring:
  config:
    activate:
      on-profile: peer1
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/

---
server:
  port: 8762
spring:
  config:
    activate:
      on-profile: peer2
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/

---
server:
  port: 8763
spring:
  config:
    activate:
      on-profile: peer3
eureka:
  instance:
    hostname: peer3
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka