mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  main:
    web-application-type: reactive
  freemarker:
    prefer-file-system-access: false
  application:
    name: microservice-gateway
  profiles:
    active: cluster1
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: SYSTEM
    password: peng414607
    driver-class-name: oracle.jdbc.OracleDriver

server:
  port: 8080

